# Generated by Django 4.1.2 on 2022-11-01 11:11

from django.db import migrations, models
import django.db.models.deletion
import pictures.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cartao', models.CharField(max_length=50, verbose_name='Número do Cartão')),
                ('finalidade', models.CharField(choices=[('D', 'Debito'), ('C', 'Credito')], default='D', max_length=1)),
                ('validade', models.DateField()),
                ('situacao', models.BooleanField(verbose_name='Aprovado')),
                ('cvv', models.CharField(max_length=4, verbose_name='CVV')),
                ('vencimento_fatura', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=15)),
                ('endereco', models.CharField(max_length=250, verbose_name='endereço')),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('foto', pictures.models.PictureField(aspect_ratios=[None, '1/1', '3/2', '16/9'], breakpoints={'l': 1200, 'm': 992, 's': 768, 'xl': 1400, 'xs': 576}, container_width=1200, file_types=['WEBP'], grid_columns=12, pixel_densities=[1, 2], upload_to='galeria')),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_conta', models.CharField(max_length=50, verbose_name='Número da Conta')),
                ('agencia', models.CharField(max_length=30)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprovacao', models.BooleanField(verbose_name='Aprovado')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('taxa_juros', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Taxa de juros')),
                ('parcelas_pagas', models.IntegerField(verbose_name='Parcelas pagas')),
                ('valor_com_juros', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor com juros')),
                ('funcionarios', models.CharField(choices=[('L', 'Larissa'), ('L', 'Brian'), ('L', 'Icaro')], default='L', max_length=1)),
                ('Justificativa', models.CharField(max_length=255)),
                ('fk_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.cliente', verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senha', models.CharField(max_length=255)),
                ('fk_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.cliente', verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destinatario', to='cadastro.cliente')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remetente', to='cadastro.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento_emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vencimento', models.DateField()),
                ('pagamento', models.DateField()),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da parcela')),
                ('fk_emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.emprestimo', verbose_name='Aprovação')),
            ],
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_fatura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento_efetuado', models.DateField(verbose_name='Data de efetivação do pagamento')),
                ('data_validade', models.DateField(verbose_name='Data de Validade')),
                ('fk_cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.cartao', verbose_name='Cartão')),
            ],
        ),
        migrations.CreateModel(
            name='Extrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField()),
                ('operacao', models.CharField(choices=[('I', 'Entrada'), ('O', 'Saida')], default='I', max_length=1)),
                ('descritivo', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fk_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.conta', verbose_name='Conta')),
            ],
        ),
        migrations.CreateModel(
            name='Contatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorito', to='cadastro.cliente')),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titular', to='cadastro.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='conta',
            name='fk_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.usuario', verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='cartao',
            name='fk_conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.conta', verbose_name='Conta'),
        ),
    ]
