# Generated by Django 4.1.2 on 2022-11-24 12:17

from django.db import migrations, models
import pictures.models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='foto',
            field=pictures.models.PictureField(aspect_ratios=[None], breakpoints={'l': 1200, 'm': 992, 's': 768, 'xl': 1400, 'xs': 576}, container_width=1200, file_types=['WEBP'], grid_columns=12, pixel_densities=[1, 2], upload_to='galeria'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='aprovacao',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='funcionarios',
            field=models.CharField(choices=[('L', 'Larissa'), ('B', 'Brian'), ('I', 'Icaro')], default='L', max_length=1),
        ),
        migrations.AlterField(
            model_name='extrato',
            name='horario',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
