# Generated by Django 4.1.3 on 2022-11-30 13:00

from django.db import migrations
import pictures.models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_remove_cliente_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto',
            field=pictures.models.PictureField(aspect_ratios=[None], breakpoints={'l': 1200, 'm': 992, 's': 768, 'xl': 1400, 'xs': 576}, container_width=1200, default=1, file_types=['WEBP'], grid_columns=12, pixel_densities=[1, 2], upload_to='galeria'),
            preserve_default=False,
        ),
    ]
