# Generated by Django 4.1.3 on 2022-11-30 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_cliente_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='foto',
        ),
    ]
